// Un día mundial por semana e o tema amplo que inspira. Escóllese polo día que cae dentro da semana,
// así que serve para calquera ano. Nun ano futuro poderían engadirse outras propostas para as mesmas semanas.
export const DAYS = [
  [1, 4, 'puntos'],
  [1, 11, 'grazas'],
  [1, 14, 'labirintos'],
  [1, 18, 'neve'],
  [1, 24, 'escola'],
  [1, 30, 'paz'],
  [2, 2, 'lagoas'],
  [2, 9, 'internet'],
  [2, 11, 'ciencia'],
  [2, 13, 'radio'],
  [2, 18, 'baleas'],
  [2, 21, 'palabras'],
  [2, 27, 'xeo'],
  [3, 3, 'salvaxes'],
  [3, 8, 'mulleres'],
  [3, 14, 'circulos'],
  [3, 21, 'arbores'],
  [3, 27, 'mascaras'],
  [4, 2, 'contos'],
  [4, 7, 'corpo'],
  [4, 12, 'espazo'],
  [4, 18, 'monumentos'],
  [4, 22, 'terra'],
  [4, 23, 'libros'],
  [4, 29, 'bailar'],
  [5, 4, 'galaxias'],
  [5, 10, 'paxaros'],
  [5, 15, 'familias'],
  [5, 18, 'museos'],
  [5, 22, 'bichos'],
  [5, 28, 'xogos'],
  [6, 3, 'bicicletas'],
  [6, 8, 'mar'],
  [6, 12, 'sombras'],
  [6, 17, 'desertos'],
  [6, 21, 'musica'],
  [6, 23, 'deportes'],
  [6, 30, 'ceonoite'],
  [7, 7, 'doces'],
  [7, 11, 'cidades'],
  [7, 17, 'caras'],
  [7, 20, 'lua'],
  [7, 24, 'nadar'],
  [7, 29, 'felinos'],
  [7, 30, 'amizades'],
  [8, 1, 'risas'],
  [8, 8, 'gatos'],
  [8, 12, 'elefantes'],
  [8, 19, 'fotos'],
  [8, 26, 'cans'],
  [9, 2, 'froitas'],
  [9, 8, 'letras'],
  [9, 13, 'chuvia'],
  [9, 16, 'ceo'],
  [9, 22, 'rua'],
  [9, 27, 'viaxes'],
  [10, 4, 'animais'],
  [10, 9, 'cartas'],
  [10, 16, 'comida'],
  [10, 20, 'cociña'],
  [10, 24, 'bibliotecas'],
  [10, 31, 'monstros'],
  [11, 5, 'ondas'],
  [11, 10, 'inventos'],
  [11, 13, 'abrazos'],
  [11, 16, 'cores'],
  [11, 21, 'pantallas'],
  [11, 24, 'dinosauros'],
  [11, 29, 'mans'],
  [12, 5, 'baixoterra'],
  [12, 11, 'montanas'],
  [12, 14, 'monos'],
  [12, 21, 'noite'],
  [12, 28, 'festas'],
]

export const THEMES = {
  grazas: { gl: 'Grazas', es: 'Gracias', ca: 'Gràcies', eu: 'Eskerrak', it: 'Grazie', pt: 'Obrigado', de: 'Danke', en: 'Thank you' },
  internet: { gl: 'Internet', es: 'Internet', ca: 'Internet', eu: 'Internet', it: 'Internet', pt: 'Internet', de: 'Internet', en: 'The internet' },
  sombras: { gl: 'Sombras', es: 'Sombras', ca: 'Ombres', eu: 'Itzalak', it: 'Ombre', pt: 'Sombras', de: 'Schatten', en: 'Shadows' },
  nadar: { gl: 'Nadar', es: 'Nadar', ca: 'Nedar', eu: 'Igeri egin', it: 'Nuotare', pt: 'Nadar', de: 'Schwimmen', en: 'Swimming' },
  chuvia: { gl: 'Chuvia', es: 'Lluvia', ca: 'Pluja', eu: 'Euria', it: 'Pioggia', pt: 'Chuva', de: 'Regen', en: 'Rain' },
  cociña: { gl: 'A cociña', es: 'La cocina', ca: 'La cuina', eu: 'Sukaldea', it: 'La cucina', pt: 'A cozinha', de: 'Die Küche', en: 'The kitchen' },
  cores: { gl: 'Cores', es: 'Colores', ca: 'Colors', eu: 'Koloreak', it: 'Colori', pt: 'Cores', de: 'Farben', en: 'Colours' },
  lagoas: { gl: 'Lagoas', es: 'Lagunas', ca: 'Llacunes', eu: 'Urmaelak', it: 'Paludi', pt: 'Lagoas', de: 'Feuchtgebiete', en: 'Wetlands' },
  baleas: { gl: 'Baleas', es: 'Ballenas', ca: 'Balenes', eu: 'Baleak', it: 'Balene', pt: 'Baleias', de: 'Wale', en: 'Whales' },
  xeo: { gl: 'Xeo', es: 'Hielo', ca: 'Gel', eu: 'Izotza', it: 'Ghiaccio', pt: 'Gelo', de: 'Eis', en: 'Ice' },
  corpo: { gl: 'O corpo', es: 'El cuerpo', ca: 'El cos', eu: 'Gorputza', it: 'Il corpo', pt: 'O corpo', de: 'Der Körper', en: 'The body' },
  monumentos: { gl: 'Monumentos', es: 'Monumentos', ca: 'Monuments', eu: 'Monumentuak', it: 'Monumenti', pt: 'Monumentos', de: 'Denkmäler', en: 'Monuments' },
  galaxias: { gl: 'Galaxias', es: 'Galaxias', ca: 'Galàxies', eu: 'Galaxiak', it: 'Galassie', pt: 'Galáxias', de: 'Galaxien', en: 'Galaxies' },
  familias: { gl: 'Familias', es: 'Familias', ca: 'Famílies', eu: 'Familiak', it: 'Famiglie', pt: 'Famílias', de: 'Familien', en: 'Families' },
  xogos: { gl: 'Xogos', es: 'Juegos', ca: 'Jocs', eu: 'Jolasak', it: 'Giochi', pt: 'Jogos', de: 'Spiele', en: 'Games' },
  deportes: { gl: 'Deportes', es: 'Deportes', ca: 'Esports', eu: 'Kirolak', it: 'Sport', pt: 'Desportos', de: 'Sport', en: 'Sports' },
  caras: { gl: 'Caras', es: 'Caras', ca: 'Cares', eu: 'Aurpegiak', it: 'Facce', pt: 'Caras', de: 'Gesichter', en: 'Faces' },
  risas: { gl: 'Risas', es: 'Risas', ca: 'Rialles', eu: 'Barreak', it: 'Risate', pt: 'Risos', de: 'Lachen', en: 'Laughter' },
  elefantes: { gl: 'Elefantes', es: 'Elefantes', ca: 'Elefants', eu: 'Elefanteak', it: 'Elefanti', pt: 'Elefantes', de: 'Elefanten', en: 'Elephants' },
  ondas: { gl: 'Ondas', es: 'Olas', ca: 'Onades', eu: 'Olatuak', it: 'Onde', pt: 'Ondas', de: 'Wellen', en: 'Waves' },
  dinosauros: { gl: 'Dinosauros', es: 'Dinosaurios', ca: 'Dinosaures', eu: 'Dinosauroak', it: 'Dinosauri', pt: 'Dinossauros', de: 'Dinosaurier', en: 'Dinosaurs' },
  monos: { gl: 'Monos', es: 'Monos', ca: 'Micos', eu: 'Tximinoak', it: 'Scimmie', pt: 'Macacos', de: 'Affen', en: 'Monkeys' },
  puntos: { gl: 'Puntos', es: 'Puntos', ca: 'Punts', eu: 'Puntuak', it: 'Punti', pt: 'Pontos', de: 'Punkte', en: 'Dots' },
  labirintos: { gl: 'Labirintos', es: 'Laberintos', ca: 'Laberints', eu: 'Labirintoak', it: 'Labirinti', pt: 'Labirintos', de: 'Labyrinthe', en: 'Mazes' },
  neve: { gl: 'Neve', es: 'Nieve', ca: 'Neu', eu: 'Elurra', it: 'Neve', pt: 'Neve', de: 'Schnee', en: 'Snow' },
  escola: { gl: 'A escola', es: 'La escuela', ca: 'L’escola', eu: 'Eskola', it: 'La scuola', pt: 'A escola', de: 'Die Schule', en: 'School' },
  paz: { gl: 'A paz', es: 'La paz', ca: 'La pau', eu: 'Bakea', it: 'La pace', pt: 'A paz', de: 'Frieden', en: 'Peace' },
  ciencia: { gl: 'Ciencia', es: 'Ciencia', ca: 'Ciència', eu: 'Zientzia', it: 'Scienza', pt: 'Ciência', de: 'Wissenschaft', en: 'Science' },
  radio: { gl: 'A radio', es: 'La radio', ca: 'La ràdio', eu: 'Irratia', it: 'La radio', pt: 'A rádio', de: 'Radio', en: 'Radio' },
  palabras: { gl: 'Palabras', es: 'Palabras', ca: 'Paraules', eu: 'Hitzak', it: 'Parole', pt: 'Palavras', de: 'Wörter', en: 'Words' },
  salvaxes: { gl: 'Animais salvaxes', es: 'Animales salvajes', ca: 'Animals salvatges', eu: 'Basapiztiak', it: 'Animali selvatici', pt: 'Animais selvagens', de: 'Wilde Tiere', en: 'Wild animals' },
  mulleres: { gl: 'Mulleres', es: 'Mujeres', ca: 'Dones', eu: 'Emakumeak', it: 'Donne', pt: 'Mulheres', de: 'Frauen', en: 'Women' },
  circulos: { gl: 'Círculos', es: 'Círculos', ca: 'Cercles', eu: 'Zirkuluak', it: 'Cerchi', pt: 'Círculos', de: 'Kreise', en: 'Circles' },
  arbores: { gl: 'Árbores', es: 'Árboles', ca: 'Arbres', eu: 'Zuhaitzak', it: 'Alberi', pt: 'Árvores', de: 'Bäume', en: 'Trees' },
  mascaras: { gl: 'Máscaras', es: 'Máscaras', ca: 'Màscares', eu: 'Maskarak', it: 'Maschere', pt: 'Máscaras', de: 'Masken', en: 'Masks' },
  contos: { gl: 'Contos', es: 'Cuentos', ca: 'Contes', eu: 'Ipuinak', it: 'Fiabe', pt: 'Contos', de: 'Märchen', en: 'Tales' },
  espazo: { gl: 'O espazo', es: 'El espacio', ca: 'L’espai', eu: 'Espazioa', it: 'Lo spazio', pt: 'O espaço', de: 'Weltraum', en: 'Space' },
  terra: { gl: 'A Terra', es: 'La Tierra', ca: 'La Terra', eu: 'Lurra', it: 'La Terra', pt: 'A Terra', de: 'Die Erde', en: 'The Earth' },
  libros: { gl: 'Libros', es: 'Libros', ca: 'Llibres', eu: 'Liburuak', it: 'Libri', pt: 'Livros', de: 'Bücher', en: 'Books' },
  bailar: { gl: 'Bailar', es: 'Bailar', ca: 'Ballar', eu: 'Dantza', it: 'Ballare', pt: 'Dançar', de: 'Tanzen', en: 'Dancing' },
  paxaros: { gl: 'Paxaros', es: 'Pájaros', ca: 'Ocells', eu: 'Txoriak', it: 'Uccelli', pt: 'Pássaros', de: 'Vögel', en: 'Birds' },
  museos: { gl: 'Museos', es: 'Museos', ca: 'Museus', eu: 'Museoak', it: 'Musei', pt: 'Museus', de: 'Museen', en: 'Museums' },
  bichos: { gl: 'Bichos', es: 'Bichos', ca: 'Bestioles', eu: 'Zomorroak', it: 'Insetti', pt: 'Bichos', de: 'Krabbeltiere', en: 'Bugs' },
  bicicletas: { gl: 'Bicicletas', es: 'Bicicletas', ca: 'Bicicletes', eu: 'Bizikletak', it: 'Biciclette', pt: 'Bicicletas', de: 'Fahrräder', en: 'Bicycles' },
  mar: { gl: 'O mar', es: 'El mar', ca: 'El mar', eu: 'Itsasoa', it: 'Il mare', pt: 'O mar', de: 'Das Meer', en: 'The sea' },
  desertos: { gl: 'Desertos', es: 'Desiertos', ca: 'Deserts', eu: 'Basamortuak', it: 'Deserti', pt: 'Desertos', de: 'Wüsten', en: 'Deserts' },
  musica: { gl: 'Música', es: 'Música', ca: 'Música', eu: 'Musika', it: 'Musica', pt: 'Música', de: 'Musik', en: 'Music' },
  ceonoite: { gl: 'O ceo de noite', es: 'El cielo nocturno', ca: 'El cel nocturn', eu: 'Gaueko zerua', it: 'Il cielo notturno', pt: 'O céu noturno', de: 'Nachthimmel', en: 'The night sky' },
  doces: { gl: 'Doces', es: 'Dulces', ca: 'Dolços', eu: 'Gozokiak', it: 'Dolci', pt: 'Doces', de: 'Süßes', en: 'Sweets' },
  cidades: { gl: 'Cidades', es: 'Ciudades', ca: 'Ciutats', eu: 'Hiriak', it: 'Città', pt: 'Cidades', de: 'Städte', en: 'Cities' },
  lua: { gl: 'A Lúa', es: 'La Luna', ca: 'La Lluna', eu: 'Ilargia', it: 'La Luna', pt: 'A Lua', de: 'Der Mond', en: 'The Moon' },
  felinos: { gl: 'Felinos', es: 'Felinos', ca: 'Felins', eu: 'Felidoak', it: 'Felini', pt: 'Felinos', de: 'Katzenartige', en: 'Big cats' },
  amizades: { gl: 'Amizades', es: 'Amistades', ca: 'Amistats', eu: 'Adiskidetasuna', it: 'Amicizie', pt: 'Amizades', de: 'Freundschaft', en: 'Friendship' },
  gatos: { gl: 'Gatos', es: 'Gatos', ca: 'Gats', eu: 'Katuak', it: 'Gatti', pt: 'Gatos', de: 'Katzen', en: 'Cats' },
  fotos: { gl: 'Fotos', es: 'Fotos', ca: 'Fotos', eu: 'Argazkiak', it: 'Foto', pt: 'Fotos', de: 'Fotos', en: 'Photos' },
  cans: { gl: 'Cans', es: 'Perros', ca: 'Gossos', eu: 'Txakurrak', it: 'Cani', pt: 'Cães', de: 'Hunde', en: 'Dogs' },
  froitas: { gl: 'Froitas', es: 'Frutas', ca: 'Fruites', eu: 'Fruituak', it: 'Frutta', pt: 'Frutas', de: 'Früchte', en: 'Fruit' },
  letras: { gl: 'Letras', es: 'Letras', ca: 'Lletres', eu: 'Letrak', it: 'Lettere', pt: 'Letras', de: 'Buchstaben', en: 'Letters' },
  ceo: { gl: 'O ceo', es: 'El cielo', ca: 'El cel', eu: 'Zerua', it: 'Il cielo', pt: 'O céu', de: 'Der Himmel', en: 'The sky' },
  rua: { gl: 'A rúa', es: 'La calle', ca: 'El carrer', eu: 'Kalea', it: 'La strada', pt: 'A rua', de: 'Die Straße', en: 'The street' },
  viaxes: { gl: 'Viaxes', es: 'Viajes', ca: 'Viatges', eu: 'Bidaiak', it: 'Viaggi', pt: 'Viagens', de: 'Reisen', en: 'Travel' },
  animais: { gl: 'Animais', es: 'Animales', ca: 'Animals', eu: 'Animaliak', it: 'Animali', pt: 'Animais', de: 'Tiere', en: 'Animals' },
  cartas: { gl: 'Cartas', es: 'Cartas', ca: 'Cartes', eu: 'Gutunak', it: 'Lettere', pt: 'Cartas', de: 'Briefe', en: 'Letters by post' },
  comida: { gl: 'Comida', es: 'Comida', ca: 'Menjar', eu: 'Janaria', it: 'Cibo', pt: 'Comida', de: 'Essen', en: 'Food' },
  bibliotecas: { gl: 'Bibliotecas', es: 'Bibliotecas', ca: 'Biblioteques', eu: 'Liburutegiak', it: 'Biblioteche', pt: 'Bibliotecas', de: 'Bibliotheken', en: 'Libraries' },
  monstros: { gl: 'Monstros', es: 'Monstruos', ca: 'Monstres', eu: 'Munstroak', it: 'Mostri', pt: 'Monstros', de: 'Monster', en: 'Monsters' },
  inventos: { gl: 'Inventos', es: 'Inventos', ca: 'Invents', eu: 'Asmakizunak', it: 'Invenzioni', pt: 'Invenções', de: 'Erfindungen', en: 'Inventions' },
  abrazos: { gl: 'Abrazos', es: 'Abrazos', ca: 'Abraçades', eu: 'Besarkadak', it: 'Abbracci', pt: 'Abraços', de: 'Umarmungen', en: 'Hugs' },
  pantallas: { gl: 'Pantallas', es: 'Pantallas', ca: 'Pantalles', eu: 'Pantailak', it: 'Schermi', pt: 'Ecrãs', de: 'Bildschirme', en: 'Screens' },
  mans: { gl: 'Mans', es: 'Manos', ca: 'Mans', eu: 'Eskuak', it: 'Mani', pt: 'Mãos', de: 'Hände', en: 'Hands' },
  baixoterra: { gl: 'Baixo terra', es: 'Bajo tierra', ca: 'Sota terra', eu: 'Lurpean', it: 'Sottoterra', pt: 'Debaixo da terra', de: 'Unter der Erde', en: 'Underground' },
  montanas: { gl: 'Montañas', es: 'Montañas', ca: 'Muntanyes', eu: 'Mendiak', it: 'Montagne', pt: 'Montanhas', de: 'Berge', en: 'Mountains' },
  noite: { gl: 'A noite', es: 'La noche', ca: 'La nit', eu: 'Gaua', it: 'La notte', pt: 'A noite', de: 'Die Nacht', en: 'The night' },
  festas: { gl: 'Festas', es: 'Fiestas', ca: 'Festes', eu: 'Jaiak', it: 'Feste', pt: 'Festas', de: 'Feste', en: 'Celebrations' },
}

// Tema da semana que empeza o luns dado (Date en hora local).
export function themeFor(monday, lang = 'gl') {
  for (let i = 0; i < 7; i++) {
    const d = new Date(monday.getTime()); d.setDate(d.getDate() + i)
    const hit = DAYS.find(([m, day]) => m === d.getMonth() + 1 && day === d.getDate())
    if (hit) return { key: hit[2], name: (THEMES[hit[2]] || {})[lang] || THEMES[hit[2]].gl, day: d }
  }
  return null
}
